from selenium import webdriver
from time import sleep

driver = webdriver.Chrome()
driver.get("https://instagram.com")
sleep(2)
email_box = driver.find_element_by_xpath('/html/body/div[1]/section/main/article/div[2]/div[1]/div/form/div/div[1]/div/label/input')
email_box.send_keys("myfoodpod@gmail.com")
sleep(2)
pass_box = driver.find_element_by_xpath('/html/body/div[1]/section/main/article/div[2]/div[1]/div/form/div/div[2]/div/label/input')
pass_box.send_keys("IIT9700PILOT")
sleep(2)
login_button = driver.find_element_by_xpath('/html/body/div[1]/section/main/article/div[2]/div[1]/div/form/div/div[3]/button')
login_button.click()
sleep(5)
login_info = driver.find_element_by_xpath('/html/body/div[1]/section/main/div/div/div/div/button')
login_info.click()
sleep(5)
notify = driver.find_element_by_xpath('/html/body/div[4]/div/div/div/div[3]/button[2]')
notify.click()
sleep(2)
profile_pic = driver.find_element_by_xpath('/html/body/div[1]/section/nav/div[2]/div/div/div[3]/div/div[5]/span/img')
profile_pic.click()
sleep(2)
profile_drop = driver.find_element_by_xpath('/html/body/div[1]/section/nav/div[2]/div/div/div[3]/div/div[5]/div[2]/div[2]/div[2]/a[1]/div')
profile_drop.click()